Repository JuanCaballero09/Proyecto-Formativo, pull requests merged in 2025-04, with the labels that each got.

#8 Docs
  docs/index.html
Labels: enhancement

#10 PDF
  PDFdocs/Diagrama_Clase.pdf
  PDFdocs/Diagrama_Entidad_Relacion.pdf
Labels: documentation

#9 Devise01
  .devcontainer/Dockerfile
  .devcontainer/create-db-user.sql
  .devcontainer/devcontainer.json
  .devcontainer/docker-compose.yml
  Gemfile
  Gemfile.lock
  app/controllers/home_controller.rb
  app/helpers/home_helper.rb
  app/models/user.rb
  app/views/devise/confirmations/new.html.erb
  app/views/devise/mailer/confirmation_instructions.html.erb
  app/views/devise/mailer/email_changed.html.erb
  app/views/devise/mailer/password_change.html.erb
  app/views/devise/mailer/reset_password_instructions.html.erb
  app/views/devise/mailer/unlock_instructions.html.erb
  app/views/devise/passwords/edit.html.erb
  app/views/devise/passwords/new.html.erb
  app/views/devise/registrations/edit.html.erb
  app/views/devise/registrations/new.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/devise/shared/_error_messages.html.erb
  app/views/devise/shared/_links.html.erb
  app/views/devise/unlocks/new.html.erb
  app/views/home/index.html.erb
  config/database.yml
  config/initializers/devise.rb
  config/locales/devise.en.yml
  config/routes.rb
  db/migrate/20250423170409_devise_create_users.rb
  db/schema.rb
  test/controllers/home_controller_test.rb
  test/fixtures/users.yml
  test/models/user_test.rb
Labels: dependencies

#17 Pagina Documentación
  docs/PDF/Diagrama_Clase.pdf
  docs/PDF/Diagrama_Entidad_Relacion.pdf
  docs/assets/img/icons/LogoTerrazaDelPri.svg
  docs/assets/img/icons/LogoTerrazaDelPri2.svg
  docs/assets/js/script.js
  docs/assets/style/bootstrap.min.css
  docs/assets/style/style1.css
  docs/index.html
  docs/views/docs.html
  docs/views/faq.html
  docs/views/home.html
  docs/views/integrantes.html
  docs/views/tecnico.html
  docs/views/usuario.html
Labels: enhancement

#23 subir mackup
  docs/PDF/macckup30-04-2025 15.36.pdf
  docs/views/docs.html
Labels: enhancement
